version: '3.8'

services:
  app:
    build: .
    ports:
      - "8005:8005"
    volumes:
      - .:/app
      - media-data:/app/media
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - DEBUG=${DEBUG}
      - DATA_UPLOAD_MAX_MEMORY_SIZE=52428800
      - FILE_UPLOAD_MAX_MEMORY_SIZE=52428800
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - media-data:/app/media
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  media-data: