# Generated by Django 5.2.2 on 2025-06-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0002_remove_cart_user_remove_order_user_cart_session_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Qayta ishlanmoqda'), ('shipped', 'Jo‘natildi'), ('delivered', 'Yetkazib berildi'), ('completed', 'Bajarildi'), ('canceled', 'Bekor qilingan')], default='pending', max_length=20),
        ),
    ]
