# Generated by Django 5.2.2 on 2025-06-05 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0003_remove_product_stock_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('tashkent_city', 'Toshkent shahri'), ('andijan_city', 'Andijon shahri'), ('bukhara_city', 'Buxoro shahri'), ('fergana_city', 'Farg‘ona shahri'), ('jizzakh_city', 'Jizzax shahri'), ('urgench', 'Urganch'), ('namangan_city', 'Namangan shahri'), ('navoiy_city', 'Navoiy shahri'), ('qarshi', 'Qarshi'), ('samarqand_city', 'Samarqand shahri'), ('guliston', 'Guliston'), ('termiz', 'Termiz'), ('nukus', 'Nukus')], default=1, max_length=50, verbose_name='Shahar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('tashkent', 'Toshkent'), ('andijan', 'Andijon'), ('bukhara', 'Buxoro'), ('fergana', 'Farg‘ona'), ('jizzakh', 'Jizzax'), ('khorezm', 'Xorazm'), ('namangan', 'Namangan'), ('navoiy', 'Navoiy'), ('qashqadaryo', 'Qashqadaryo'), ('samarqand', 'Samarqand'), ('sirdaryo', 'Sirdaryo'), ('surxondaryo', 'Surxondaryo'), ('karakalpakstan', 'Qoraqalpog‘iston')], default=1, max_length=50, verbose_name='Viloyat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Telefon raqami +998 bilan boshlanishi va 9 ta raqamdan iborat bo‘lishi kerak (masalan, +998901234567).', regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam'),
        ),
    ]
