# Generated by Django 5.2.2 on 2025-06-05 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0004_remove_order_last_name_order_city_order_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998 bilan boshlanishi va 9 ta raqamdan iborat bo'lishi kerak (masalan, +998901234567).", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam'),
        ),
    ]
