# Generated by Django 5.2.2 on 2025-06-05 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0005_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998 bilan boshlanishi va 9 ta raqamdan iborat bo'lishi kerak", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam'),
        ),
    ]
