# Generated by Django 5.2.2 on 2025-06-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0007_order_notes_alter_order_city_alter_order_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Admin izohlari'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'shimcha manzil izohi"),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('samarqand', 'Samarqand')], default='samarqand', max_length=50, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('boglandi', "Bog'landi"), ('bekor_qilindi', 'Bekor qilindi')], default='kutilmoqda', max_length=20),
        ),
    ]
