# Generated by Django 5.2.2 on 2025-06-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0008_order_admin_notes_alter_order_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('boglandi', "Bog'landi"), ('bajarildi', 'Bajarildi'), ('bekor_qilindi', 'Bekor qilindi')], default='kutilmoqda', max_length=20),
        ),
    ]
