# Generated by Django 5.2.2 on 2025-06-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0012_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
